// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	keeper "keeper/proto"

	mock "github.com/stretchr/testify/mock"
)

// KeeperServiceClient is an autogenerated mock type for the KeeperServiceClient type
type KeeperServiceClient struct {
	mock.Mock
}

// Command provides a mock function with given fields: ctx, opts
func (_m *KeeperServiceClient) Command(ctx context.Context, opts ...grpc.CallOption) (keeper.KeeperService_CommandClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Command")
	}

	var r0 keeper.KeeperService_CommandClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (keeper.KeeperService_CommandClient, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) keeper.KeeperService_CommandClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keeper.KeeperService_CommandClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) Login(ctx context.Context, in *keeper.LoginRequest, opts ...grpc.CallOption) (*keeper.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *keeper.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *keeper.LoginRequest, ...grpc.CallOption) (*keeper.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *keeper.LoginRequest, ...grpc.CallOption) *keeper.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keeper.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *keeper.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) Register(ctx context.Context, in *keeper.RegisterRequest, opts ...grpc.CallOption) (*keeper.RegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *keeper.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *keeper.RegisterRequest, ...grpc.CallOption) (*keeper.RegisterResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *keeper.RegisterRequest, ...grpc.CallOption) *keeper.RegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keeper.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *keeper.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKeeperServiceClient creates a new instance of KeeperServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeeperServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeeperServiceClient {
	mock := &KeeperServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
