// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"
	service "keeper/internal/server/service"

	mock "github.com/stretchr/testify/mock"

	storage "keeper/internal/server/storage"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// AddClient provides a mock function with given fields: ctx, clientID, username, state
func (_m *Provider) AddClient(ctx context.Context, clientID string, username string, state service.State) error {
	ret := _m.Called(ctx, clientID, username, state)

	if len(ret) == 0 {
		panic("no return value specified for AddClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, service.State) error); ok {
		r0 = rf(ctx, clientID, username, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateData provides a mock function with given fields: ctx, username, title, data_type, data
func (_m *Provider) CreateData(ctx context.Context, username string, title string, data_type service.DataType, data string) error {
	ret := _m.Called(ctx, username, title, data_type, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, service.DataType, string) error); ok {
		r0 = rf(ctx, username, title, data_type, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, username, password
func (_m *Provider) CreateUser(ctx context.Context, username string, password string) error {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExistUser provides a mock function with given fields: ctx, username, password
func (_m *Provider) ExistUser(ctx context.Context, username string, password string) error {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for ExistUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllClients provides a mock function with given fields: ctx
func (_m *Provider) GetAllClients(ctx context.Context) ([]storage.Client, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllClients")
	}

	var r0 []storage.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]storage.Client, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []storage.Client); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetData provides a mock function with given fields: ctx, username, title
func (_m *Provider) GetData(ctx context.Context, username string, title string) (string, error) {
	ret := _m.Called(ctx, username, title)

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, username, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, title)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTitlesByUser provides a mock function with given fields: ctx, username
func (_m *Provider) GetTitlesByUser(ctx context.Context, username string) ([]string, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetTitlesByUser")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *Provider) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveClient provides a mock function with given fields: ctx, clientID
func (_m *Provider) RemoveClient(ctx context.Context, clientID string) error {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateClientState provides a mock function with given fields: ctx, clientID, state
func (_m *Provider) UpdateClientState(ctx context.Context, clientID string, state service.State) error {
	ret := _m.Called(ctx, clientID, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClientState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.State) error); ok {
		r0 = rf(ctx, clientID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
